const Dados_Categorias_E_Palavras = [
{Categoria:"Paises",Dicas:"Tem Ordem e progresso na bandeira",Palavra:"Brasil"},
{Categoria:"Paises",Dicas:"São Unidos",Palavra:"EstadosUnidos"},
{Categoria:"Paises",Dicas:"Tem olho puxado mais não japonês",Palavra:"China"},
{Categoria:"Paises",Dicas:"1945 ficou marcado na história desse Pais",Pais:"Japão"},
{Categoria:"Paises",Dicas:"Tem muitos tanques de guerras",Palavra:"Russia"},
{Categoria:"Paises",Dicas:"É a terra dos vulcões",Palavra:"Chile"},
{Categoria:"Paises",Dicas:"É conhecido por usas Preciosas Esmeralda",Palavra:"Colômbia"},
{Categoria:"Paises",Dicas:"É rica em fósseis de Dinossauro",Palavra:"Argentina"},
{Categoria:"Paises",Dicas:"É um Pais que tem Duas Línguas" ,Palavra:"Canada"},
{Categoria:"Paises",Dicas:"Capital mais antiga das Américas",Palavra:"Mexico"},
{Categoria:"Objetos",Dicas:"Serve para colocar Água",Palavra:"Balde"},
{Categoria:"Objetos",Dicas:"Fica em cima das casas",Palavra:"Telhado"},
{Categoria:"Objetos",Dicas:"É Parente Da Faca",Palavra:"Adaga"},
{Categoria:"Objetos",Dicas:"Ela é pequena mais Fura",Palavra:"Agulha"},
{Categoria:"Objetos",Dicas:"Ele enche de Gazes e pode Estourar",Palavra:"Balões"},
{Categoria:"Objetos",Dicas:"Você pode Sentar-se",Palavra:"Banco"},
{Categoria:"Objetos",Dicas:"Serve para colocar Liquido",Palavra:"Copo"},
{Categoria:"Objetos",Dicas:"Usa como alternativa se não tiver garfo",Palavra:"Colheres"},
{Categoria:"Objetos",Dicas:"Tem pontos de 1 a 6 em cada lado",Palavra:"Dados"},
{Categoria:"Objetos",Dicas:"Servem para cortar",Palavra:"Facas"},
{Categoria:"Carros",Dicas:"Primeiro Carro Usado no Brasil",Palavra:"Fusca"},
{Categoria:"Carros",Dicas:"Primeiro Carro Mil",Palavra:"FiatUno"},
{Categoria:"Carros",Dicas:"Automóvel mais vendido da história",Palavra:"Corolla"},
{Categoria:"Carros",Dicas:"Carro que começa com a letra S",Palavra:"Siena"},
{Categoria:"Carros",Dicas:"O nome desse carro tem no campo de Futebol",Palavra:"Gol"},
{Categoria:"Carros",Dicas:"É um Gol mas tem um formato diferente",Palavra:"GolQuadrado"},
{Categoria:"Carros",Dicas:"Quando você se Coça",Palavra:"Corsa"},
{Categoria:"Carros",Dicas:"Você Deixa tudo Combinado",Palavra:"Combi"},
{Categoria:"Carros",Dicas:"Parece Caminhão mais não é",Palavra:"Caminhonete"},
{Categoria:"Carros",Dicas:"Você precisa viajar mais para isso precisa pegar a",Palavra:"Estrada"},
{Categoria:"Times",Dicas:"É o maior campeão Paulista",Palavra:"Corinthians"},
{Categoria:"Times",Dicas:"É o Maior Campeão Brasileiro",Palavra:"Palmeiras"},
{Categoria:"Times",Dicas:"Time Que Parou uma Guerra",Palavra:"Santos"},
{Categoria:"Times",Dicas:"Tem Três mundiais",Palavra:"SaoPaulo"},
{Categoria:"Times",Dicas:"Time que pulo da Serie C para Serie A", Palavra:"Fluminense"},
{Categoria:"Times",Dicas:"Tem Quatro Rebaixamentos",Palavra:"VascoDaGama"},
{Categoria:"Times",Dicas:"Antigamente não Tinha RedBull",Palavra:"Bragantino"},
{Categoria:"Times",Dicas:"Tem o Mascote Do Super Homem",Palavra:"Bahia"},
{Categoria:"Times",Dicas:"Maior campeão da copa do Brasil",Palavra:"Cruzeiro"},
{Categoria:"Times",Dicas:"Tem mais vitórias que o rival Cruzeiro",Palavra:"AtleticoMineiro"},
{Categoria:"Natureza",Dicas:"é o mais inteligente entre as espécies",Palavra:"Humanos"},
{Categoria:"Natureza",Dicas:"São Selvagens",Palavra:"Animais"},
{Categoria:"Natureza",Dicas:"Produz Oxigênio",Palavra:"Arvores"},
{Categoria:"Natureza",Dicas:"Produz Fotossíntese",Palavra:"Plantas"},
{Categoria:"Natureza",Dicas:"As pessoas tem medo desse fenômeno natural",Palavra:"Raios"},
{Categoria:"Natureza",Dicas:"Cai do céu",Palavra:"Chuva"},
{Categoria:"Natureza",Dicas:"Se formam e deixam o céu assustador",Palavra:"Nuvens"},
{Categoria:"Natureza",Dicas:"o seu corpo precisa desse elemento",Palavra:"Agua"},
{Categoria:"Natureza",Dicas:"É Muito Frio",Palavra:"Gelo"},
{Categoria:"Natureza",Dicas:"Tem benefícios naturais",Palavra:"Frutas"},
];

export default Dados_Categorias_E_Palavras;