const Dados_Categorias_Palavras_Dificeis = [
{Categoria:"Paises",Palavra:"Eslovenia"        },
{Categoria:"Paises",Palavra:"Eslovaquia"       },
{Categoria:"Paises",Palavra:"Tanzania"         },
{Categoria:"Paises",Palavra:"Nigeria"          },
{Categoria:"Paises",Palavra:"Quenia"           },
{Categoria:"Paises",Palavra:"Alemanha"         },
{Categoria:"Paises",Palavra:"Andorra"          },
{Categoria:"Paises",Palavra:"Austria"          },
{Categoria:"Paises",Palavra:"Bielorrussia"     },
{Categoria:"Paises",Palavra:"Chipre"           },
{Categoria:"Objetos",Palavra:"Edredom"        },
{Categoria:"Objetos",Palavra:"Acucareiro"     },
{Categoria:"Objetos",Palavra:"Castical"       },
{Categoria:"Objetos",Palavra:"Funil"          },
{Categoria:"Objetos",Palavra:"Kimono"         },
{Categoria:"Objetos",Palavra:"Kart"           },
{Categoria:"Objetos",Palavra:"Kit"            },
{Categoria:"Objetos",Palavra:"Óculos"         },
{Categoria:"Objetos",Palavra:"Orelhao"        },
{Categoria:"Objetos",Palavra:"Picareta"       },
{Categoria:"Carros", Palavra:"Mustang"      },
{Categoria:"Carros", Palavra:"MonzaHatch"  },
{Categoria:"Carros", Palavra:"MercedesBens"},
{Categoria:"Carros", Palavra:"Bravo"        },
{Categoria:"Carros", Palavra:"HB20"         },
{Categoria:"Carros", Palavra:"I30"          },
{Categoria:"Carros", Palavra:"Etios"        },
{Categoria:"Carros", Palavra:"KA"           },
{Categoria:"Carros", Palavra:"Jetta"        },
{Categoria:"Carros", Palavra:"March"        },
{Categoria:"Natureza",Palavra:"Oxigenios"  },
{Categoria:"Natureza",Palavra:"Ventos"     },
{Categoria:"Natureza",Palavra:"Tornados"   },
{Categoria:"Natureza",Palavra:"Furacoes"   },
{Categoria:"Natureza",Palavra:"Insetos"    },
{Categoria:"Natureza",Palavra:"Vulcoes"    },
{Categoria:"Natureza",Palavra:"Gases"      },
{Categoria:"Natureza",Palavra:"Sol"        },
{Categoria:"Natureza",Palavra:"Lua"        },
{Categoria:"Natureza",Palavra:"Ceu"        },
{Categoria:"Times" ,Palavra:"Operario"       },
{Categoria:"Times" ,Palavra:"SouzaPB"       },
{Categoria:"Times" ,Palavra:"BotafogoDeSP" },
{Categoria:"Times" ,Palavra:"Mirassol"       },
{Categoria:"Times" ,Palavra:"Cianorte"       },
{Categoria:"Times" ,Palavra:"Paraná"         },
{Categoria:"Times" ,Palavra:"Comercial"      },
{Categoria:"Times" ,Palavra:"Trem"           },
{Categoria:"Times" ,Palavra:"Ferroviaria"    },
{Categoria:"Times" ,Palavra:"Chapecoence"    },
];

export default Dados_Categorias_Palavras_Dificeis;